-- AlterTable
ALTER TABLE `livro` ALTER COLUMN `updatedAt` DROP DEFAULT;

-- AlterTable
ALTER TABLE `requisicao` ADD COLUMN `despachadoEm` DATETIME(3) NULL,
    MODIFY `status` ENUM('PENDENTE', 'APROVADA', 'SAIU_PARA_ENTREGA', 'ENTREGUE', 'DEVOLVIDA', 'NEGADA') NOT NULL DEFAULT 'PENDENTE';
