// src/pages/admin/Familias.tsx (versão compacta)
import {useEffect,useMemo,useState,useCallback} from 'react'
import AOS from 'aos'
import 'aos/dist/aos.css'
import {FaSearch,FaPlus,FaEdit,FaTrash,FaSyncAlt,FaSortAlphaDown,FaChevronLeft,FaChevronRight,FaTimes,FaEye,FaBook,FaShoppingCart,FaUsers,FaCalendarAlt} from 'react-icons/fa'
import {FamiliasAdminAPI,UtilizadoresAPI,ConsultasAPI,BibliotecasAPI,type Biblioteca,type Familia as APIFamilia,type FamiliaFilho,type ID,parseApiError} from '../../api/client'
import {Toaster,toast} from 'sonner'

/* ================= Tipos ================= */
type Row={id:number;userId:number;nome:string;email:string;telefone:string;morada:string;biblioteca:string|null;interesses:string[];filhos:number;createdAt?:string|null}
 type FilhoForm={nome:string;idade:number|'';genero:'F'|'M'|'Outro'|'';perfilLeitor:'iniciante'|'Dislexia'|'autonomo'|''}
 type Requisicao={id:number;titulo?:string;data?:string;estado?:string;devolucao?:string}
 type Compra={id:number;titulo?:string;data?:string;preco?:number;qtd?:number}
 type ConsultaMini={id:number;dataHora:string;bibliotecarioNome?:string|null;status?:string|null;metodo?:string|null}

/* ================= Utils ================= */
const Chip=({children}:{children:React.ReactNode})=>(<span className="inline-flex items-center rounded-full bg-gray-100 text-gray-700 px-3 py-1 text-xs">{children}</span>)
const formatDate=(d?:string|null)=>{if(!d)return '—';const dt=new Date(d);return Number.isNaN(dt.getTime())?'—':`${dt.toLocaleDateString('pt-PT')} ${dt.toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}`}
const useDebounced=<T,>(value:T,delay=350)=>{const[v,setV]=useState(value);useEffect(()=>{const t=setTimeout(()=>setV(value),delay);return()=>clearTimeout(t)},[value,delay]);return v}
const mapFamiliaToRow=(f:APIFamilia&any):Row=>{const id=Number(f.id),nome=f.nome??f.name??f.user?.name??`Família #${id}`,email=f.email??f.user?.email??'—',telefone=f.telefone??'—',morada=f.morada??'—',biblioteca=f.bibliotecaNome??f.user?.biblioteca?.nome??(f.user?.bibliotecaId?`Biblioteca #${f.user?.bibliotecaId}`:null),filhos=Array.isArray(f.filhos)?f.filhos.length:0,interesses=Array.isArray(f.interesses)?(f.interesses as string[]):[];return{ id,userId:Number(f.userId??f.user?.id??0),nome:String(nome),email:String(email),telefone:String(telefone),morada:String(morada),biblioteca:biblioteca?String(biblioteca):null,interesses,filhos,createdAt:f.createdAt??null}}

/* ================= Componente ================= */
export default function Familias(){
  /* Tabela / filtros */
  const[q,setQ]=useState('');const dq=useDebounced(q,400);const[sort,setSort]=useState<'nome'|'createdAt'>('nome');const[order,setOrder]=useState<'asc'|'desc'>('asc');const[page,setPage]=useState(1);const[pageSize,setPageSize]=useState(12);const[total,setTotal]=useState(0);const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(false)
  /* Modais */
  const[showCreate,setShowCreate]=useState(false);const[showEditId,setShowEditId]=useState<number|null>(null);const[showDetailsId,setShowDetailsId]=useState<number|null>(null);const[detailsData,setDetailsData]=useState<APIFamilia|null>(null);const[detailsLoading,setDetailsLoading]=useState(false);const[detailsTab,setDetailsTab]=useState<'resumo'|'requisicoes'|'compras'|'consultas'|'filhos'>('resumo')
  const[detMetrics,setDetMetrics]=useState({requisicoes:0,compras:0,consultas:0,filhos:0});const[detRequisicoes,setDetRequisicoes]=useState<Requisicao[]>([]);const[detCompras,setDetCompras]=useState<Compra[]>([]);const[detConsultas,setDetConsultas]=useState<ConsultaMini[]>([])
  /* Form criar */
  const[createUserQuery,setCreateUserQuery]=useState('');const dCreateUserQuery=useDebounced(createUserQuery,400);const[createUserOptions,setCreateUserOptions]=useState<any[]>([]);const[createUserId,setCreateUserId]=useState<number|''>('');const[createTelefone,setCreateTelefone]=useState('');const[createMorada,setCreateMorada]=useState('');const[createInteresses,setCreateInteresses]=useState<string>('');const[createFilhos,setCreateFilhos]=useState<FilhoForm[]>([])
  /* Form editar */
  const[editData,setEditData]=useState<{id:number;telefone:string;morada:string;interessesCsv:string;user:{name:string;email:string;bibliotecaId:number|null|''}}|null>(null)
  /* Bibliotecas */
  const[bibliotecas,setBibliotecas]=useState<Biblioteca[]>([])

  /* Setup */
  useEffect(()=>{AOS.init({duration:600,once:true})},[]);useEffect(()=>{document.title='Gestão de Famílias'},[])
  useEffect(()=>{(async()=>{try{const res=await BibliotecasAPI.listarPublic({page:1,pageSize:300});const items=(Array.isArray(res)?res: (res as any)?.items??[]) as Biblioteca[];setBibliotecas(items.slice().sort((a,b)=>a.nome.localeCompare(b.nome)))}catch(e){console.warn('Falha a carregar bibliotecas públicas',e)}})()},[])

  /* Tabela */
  const load=useCallback(async()=>{setLoading(true);try{const params:any={page,pageSize,sort,order};if(dq.trim())params.q=dq.trim();const resp=await FamiliasAdminAPI.listar(params);const mapped=(resp.items||[]).map(mapFamiliaToRow);setRows(mapped);setTotal(resp.total??mapped.length)}catch(e){toast.error(parseApiError(e))}finally{setLoading(false)}},[page,pageSize,sort,order,dq]);useEffect(()=>{load()},[load])
  const totalPages=useMemo(()=>Math.max(1,Math.ceil(total/pageSize)),[total,pageSize]);const toggleSort=(by:'nome'|'createdAt')=>{if(sort!==by){setSort(by);setOrder('asc');setPage(1)}else{setOrder(o=>o==='asc'?'desc':'asc');setPage(1)}}
  const resetCreateForm=()=>{setCreateUserQuery('');setCreateUserOptions([]);setCreateUserId('');setCreateTelefone('');setCreateMorada('');setCreateInteresses('');setCreateFilhos([])}

  /* Buscar utilizadores PAI */
  useEffect(()=>{(async()=>{if(!dCreateUserQuery.trim()){setCreateUserOptions([]);return}try{const res=await (UtilizadoresAPI.listar as any)({q:dCreateUserQuery.trim(),role:'PAI',pageSize:10});setCreateUserOptions(res.items||[])}catch{/* noop */}})()},[dCreateUserQuery])

  /* CRUD */
  const handleCreate=async(e:React.FormEvent)=>{e.preventDefault();if(!createUserId)return toast.error('Escolhe o utilizador (PAI).');try{const payload:any={userId:Number(createUserId),telefone:createTelefone.trim(),morada:createMorada.trim(),interesses:createInteresses.split(',').map(s=>s.trim()).filter(Boolean)};if(createFilhos.length){const fv=createFilhos.filter(f=>f.nome&&f.idade!==''&&f.genero&&f.perfilLeitor);if(fv.length)payload.filhos=fv.map(f=>({nome:f.nome,idade:Number(f.idade),genero:f.genero,perfilLeitor:f.perfilLeitor}))}await FamiliasAdminAPI.criar(payload);toast.success('Família criada.');setShowCreate(false);resetCreateForm();load()}catch(e){toast.error(parseApiError(e))}}
  const addFilho=()=>setCreateFilhos(fs=>[...fs,{nome:'',idade:'',genero:'',perfilLeitor:''}]);const removeFilho=(i:number)=>setCreateFilhos(fs=>fs.filter((_,idx)=>idx!==i))
  const openEdit=async(row:Row)=>{setShowEditId(row.id);setEditData({id:row.id,telefone:row.telefone==='—'?'':row.telefone,morada:row.morada==='—'?'':row.morada,interessesCsv:row.interesses.join(', '),user:{name:row.nome,email:row.email==='—'?'':row.email,bibliotecaId:'' as any}})}
  const handleUpdate=async(e:React.FormEvent)=>{e.preventDefault();if(!editData)return;try{const payload:any={telefone:editData.telefone.trim()||undefined,morada:editData.morada.trim()||undefined,interesses:editData.interessesCsv.split(',').map(s=>s.trim()).filter(Boolean)};if((payload.interesses as string[]).length===0)delete payload.interesses;const userUpdate:any={};if(editData.user.name)userUpdate.name=editData.user.name;if(editData.user.email)userUpdate.email=editData.user.email;if(editData.user.bibliotecaId!=='')userUpdate.bibliotecaId=editData.user.bibliotecaId;if(Object.keys(userUpdate).length)payload.user=userUpdate;await FamiliasAdminAPI.atualizar(editData.id as ID,payload);toast.success('Família atualizada.');setShowEditId(null);setEditData(null);load()}catch(e){toast.error(parseApiError(e))}}
  const handleDelete=async(id:number)=>{if(!confirm('Remover esta família? (não remove o utilizador)'))return;try{await FamiliasAdminAPI.remover(id as ID);toast.success('Família removida.');load()}catch(e){toast.error(parseApiError(e))}}

  /* Detalhes */
  const openDetails=async(row:Row)=>{setShowDetailsId(row.id);setDetailsLoading(true);setDetailsData(null);setDetRequisicoes([]);setDetCompras([]);setDetConsultas([]);setDetMetrics({requisicoes:0,compras:0,consultas:0,filhos:row.filhos});setDetailsTab('resumo');try{const d=await FamiliasAdminAPI.obter(row.id as ID);setDetailsData(d);const statsP=(FamiliasAdminAPI as any).estatisticas?.(row.id).catch(()=>null),reqsP=(FamiliasAdminAPI as any).requisicoes?.(row.id).catch(()=>[]),comprasP=(FamiliasAdminAPI as any).compras?.(row.id).catch(()=>[]),consultasP=(ConsultasAPI as any)?.listar?.({familiaId:row.id,page:1,pageSize:100}).then((r:any)=>r?.items??r??[]).catch(()=>[]);const[stats,reqs,compras,consultas]=await Promise.all([statsP,reqsP,comprasP,consultasP]);if(Array.isArray(reqs))setDetRequisicoes(reqs.map((x:any)=>({id:Number(x.id),titulo:x.livroTitulo??x.titulo??x.bookTitle??`Requisição #${x.id}`,data:x.data??x.createdAt??x.requisitadoEm??x.inicio??null,estado:x.estado??x.status??x.situacao??null,devolucao:x.devolucao??x.devolvidoEm??x.fim??null})));if(Array.isArray(compras))setDetCompras(compras.map((x:any)=>({id:Number(x.id),titulo:x.titulo??x.livro?.titulo??`Compra #${x.id}`,data:x.data??x.createdAt??null,preco:typeof x.preco==='number'?x.preco:typeof x.total==='number'?x.total:undefined,qtd:x.qtd??x.quantidade??x.items?.length??undefined})));if(Array.isArray(consultas))setDetConsultas(consultas.map((c:any)=>({id:Number(c.id),dataHora:c.dataHora??c.data??c.createdAt,bibliotecarioNome:c.bibliotecarioNome??c.bibliotecario?.name??null,status:c.status??null,metodo:c.metodo??(c.notas?.match(/m[eé]todo:\s*(presencial|videochamada)/i)?.[1]?.toUpperCase()??null)})));setDetMetrics({requisicoes:Array.isArray(reqs)?reqs.length:stats?.totalRequisicoes??0,compras:Array.isArray(compras)?compras.length:stats?.totalCompras??0,consultas:Array.isArray(consultas)?consultas.length:stats?.totalConsultas??0,filhos:Array.isArray((d as any)?.filhos)?(d as any).filhos.length:row.filhos??0})}catch(e){toast.error(parseApiError(e));setShowDetailsId(null)}finally{setDetailsLoading(false)}}

  return (
  <div className="min-h-screen bg-gradient-to-br from-[#eef4ff] via-[#f8f6ff] to-[#fdf7ee] py-6 px-2 ">
    <Toaster position="top-center" richColors closeButton />
    <main className=" mx-auto">
      {/* Header */}
      <header className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4 mb-6">
        <h1 className="text-3xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-700 to-purple-700">👨‍👩‍👧 Gestão de Famílias</h1>
        <div className="flex flex-col sm:flex-row gap-2 w-full lg:w-auto">
          <div className="relative flex-1 sm:w-80"><FaSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={q} onChange={e=>{setPage(1);setQ(e.target.value)}} placeholder="Pesquisar por nome, email, telefone, morada…" className="w-full pl-9 pr-3 py-2 rounded-lg border border-blue-400 bg-white focus:ring-2 focus:ring-purple-600"/></div>
          <div className="flex gap-2 flex-wrap">
            <button onClick={()=>toggleSort('nome')} className="inline-flex items-center gap-2 bg-white px-3 py-2 rounded-lg shadow-sm border border-gray-400 hover:bg-gray-50" title="Ordenar por nome"><FaSortAlphaDown/>Nome {sort==='nome'?(order==='asc'?'↑':'↓'):''}</button>
            <button onClick={()=>toggleSort('createdAt')} className="inline-flex items-center gap-2 bg-white px-3 py-2 rounded-lg shadow-sm border border-gray-400 hover:bg-gray-50" title="Ordenar por criação"><FaSortAlphaDown/>Criada {sort==='createdAt'?(order==='asc'?'↑':'↓'):''}</button>
            <button onClick={()=>load()} className="inline-flex items-center gap-2 bg-white px-3 py-2 rounded-lg shadow-sm border border-gray-400 hover:bg-gray-50" title="Atualizar"><FaSyncAlt/>Atualizar</button>
            <button onClick={()=>{setShowCreate(true);resetCreateForm()}} className="inline-flex items-center gap-2 bg-gradient-to-r from-blue-600 to-purple-600 text-white px-3 py-2 rounded-lg shadow"><FaPlus/>Nova Família</button>
          </div>
        </div>
      </header>

      {/* Tabela */}
      <section className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full text-sm">
            <thead className="bg-blue-600 text-white"><tr><th className="px-4 py-3 text-left font-semibold">Nome</th><th className="px-4 py-3 text-left font-semibold">Email</th><th className="px-4 py-3 text-left font-semibold">Telefone</th><th className="px-4 py-3 text-left font-semibold">Morada</th><th className="px-4 py-3 text-left font-semibold">Biblioteca</th><th className="px-4 py-3 text-center font-semibold">Filhos</th><th className="px-4 py-3 text-right font-semibold w-56">Ações</th></tr></thead>
            <tbody className="divide-y">
              {loading&&(<tr><td colSpan={7} className="px-4 py-8 text-center text-gray-600">A carregar…</td></tr>)}
              {!loading&&rows.length===0&&(<tr><td colSpan={7} className="px-4 py-8 text-center text-gray-600">Nenhuma família encontrada.</td></tr>)}
              {!loading&&rows.map(r=>(<tr key={r.id} className="hover:bg-gray-50/60"><td className="px-4 py-3 whitespace-nowrap">{r.nome}</td><td className="px-4 py-3">{r.email}</td><td className="px-4 py-3">{r.telefone}</td><td className="px-4 py-3">{r.morada}</td><td className="px-4 py-3">{r.biblioteca??'—'}</td><td className="px-4 py-3 text-center">{r.filhos}</td><td className="px-4 py-2"><div className="flex items-center justify-end gap-2"><button onClick={()=>openDetails(r)} className="inline-flex items-center gap-2 px-3 py-1.5 rounded-md border border-gray-200 hover:bg-gray-50" title="Ver detalhes"><FaEye/>Detalhes</button><button onClick={()=>openEdit(r)} className="inline-flex items-center gap-2 px-3 py-1.5 rounded-md border border-gray-200 hover:bg-gray-50" title="Editar"><FaEdit/>Editar</button><button onClick={()=>handleDelete(r.id)} className="inline-flex items-center gap-2 px-3 py-1.5 rounded-md border border-red-200 text-red-600 hover:bg-red-50" title="Remover"><FaTrash/>Remover</button></div></td></tr>))}
            </tbody>
          </table>
        </div>
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3 p-3 border-t bg-gray-50">
          <div className="flex items-center gap-2"><span className="text-sm text-gray-700">Por página:</span><select value={pageSize} onChange={e=>{setPage(1);setPageSize(Number(e.target.value))}} className="px-2 py-1 rounded-md border border-gray-300 bg-white">{[6,12,24,48].map(n=>(<option key={n} value={n}>{n}</option>))}</select></div>
          <div className="flex items-center gap-3"><button disabled={page<=1||loading} onClick={()=>setPage(p=>Math.max(1,p-1))} className={`inline-flex items-center gap-2 px-3 py-2 rounded-lg border ${page<=1||loading?'bg-gray-100 text-gray-400 border-gray-200':'bg-white hover:bg-gray-50 border-gray-200'}`}><FaChevronLeft/>Anterior</button><span className="text-sm text-gray-700">Página <strong>{page}</strong> de <strong>{totalPages}</strong></span><button disabled={page>=totalPages||loading} onClick={()=>setPage(p=>Math.min(totalPages,p+1))} className={`inline-flex items-center gap-2 px-3 py-2 rounded-lg border ${page>=totalPages||loading?'bg-gray-100 text-gray-400 border-gray-200':'bg-white hover:bg-gray-50 border-gray-200'}`}>Seguinte <FaChevronRight/></button></div>
        </div>
      </section>
    </main>

    {/* MODAL: CRIAR */}
    {showCreate&&(<div className="fixed inset-0 z-50 bg-black/30 backdrop-blur-sm flex items-center justify-center p-3"><form onSubmit={handleCreate} className="w-full max-w-2xl bg-white rounded-2xl shadow-xl border p-5 relative"><button type="button" onClick={()=>setShowCreate(false)} className="absolute right-3 top-3 text-gray-500 hover:text-gray-800"><FaTimes/></button><h2 className="text-xl font-bold mb-4">Nova Família</h2>
      <div className="grid sm:grid-cols-2 gap-4">
        <div className="sm:col-span-2"><label className="text-sm text-gray-700">Procurar utilizador PAI (nome/email)</label><input value={createUserQuery} onChange={e=>setCreateUserQuery(e.target.value)} placeholder="Ex.: joao@exemplo.com" className="w-full mt-1 px-3 py-2 rounded-md border"/>{createUserOptions.length>0&&(<div className="mt-2 border rounded-md divide-y max-h-40 overflow-auto">{createUserOptions.map(u=>(<button type="button" key={u.id} onClick={()=>{setCreateUserId(u.id);setCreateUserQuery(`${u.name} <${u.email}>`)}} className={`w-full text-left px-3 py-2 hover:bg-gray-50 ${createUserId===u.id?'bg-blue-50':''}`}><div className="font-medium">{u.name}</div><div className="text-xs text-gray-600">{u.email}</div></button>))}</div>)}</div>
        <div><label className="text-sm text-gray-700">Utilizador selecionado (ID)</label><input type="number" value={createUserId} onChange={e=>setCreateUserId(e.target.value?Number(e.target.value):'')} placeholder="ID do utilizador PAI" className="w-full mt-1 px-3 py-2 rounded-md border"/></div>
        <div><label className="text-sm text-gray-700">Telefone</label><input value={createTelefone} onChange={e=>setCreateTelefone(e.target.value)} className="w-full mt-1 px-3 py-2 rounded-md border" required/></div>
        <div className="sm:col-span-2"><label className="text-sm text-gray-700">Morada</label><input value={createMorada} onChange={e=>setCreateMorada(e.target.value)} className="w-full mt-1 px-3 py-2 rounded-md border" required/></div>
        <div className="sm:col-span-2"><label className="text-sm text-gray-700">Interesses (separados por vírgula)</label><input value={createInteresses} onChange={e=>setCreateInteresses(e.target.value)} placeholder="aventura, ficção científica…" className="w-full mt-1 px-3 py-2 rounded-md border"/></div>
      </div>
      <div className="mt-5"><div className="flex items-center justify-between mb-2"><h3 className="font-semibold">Filhos (opcional)</h3><button type="button" onClick={addFilho} className="inline-flex items-center gap-2 px-3 py-1.5 rounded-md border hover:bg-gray-50"><FaPlus/>Adicionar filho</button></div>{createFilhos.length===0&&(<p className="text-sm text-gray-500">Podes adicionar depois.</p>)}{createFilhos.map((f,i)=>(<div key={i} className="grid sm:grid-cols-5 gap-3 items-end mb-2"><div className="sm:col-span-2"><label className="text-sm text-gray-700">Nome</label><input value={f.nome} onChange={e=>setCreateFilhos(fs=>fs.map((x,idx)=>idx===i?{...x,nome:e.target.value}:x))} className="w-full mt-1 px-3 py-2 rounded-md border"/></div><div><label className="text-sm text-gray-700">Idade</label><input type="number" min={0} max={18} value={f.idade} onChange={e=>{const num=e.target.value===''?'':Number(e.target.value);setCreateFilhos(fs=>fs.map((x,idx)=>idx===i?{...x,idade:num}:x))}} className="w-full mt-1 px-3 py-2 rounded-md border"/></div><div><label className="text-sm text-gray-700">Género</label><select value={f.genero||''} onChange={e=>setCreateFilhos(fs=>fs.map((x,idx)=>idx===i?{...x,genero:(e.target.value||'') as FilhoForm['genero']}:x))} className="w-full mt-1 px-3 py-2 rounded-md border bg-white"><option value="">—</option><option value="F">F</option><option value="M">M</option><option value="Outro">Outro</option></select></div><div><label className="text-sm text-gray-700">Perfil</label><select value={f.perfilLeitor||''} onChange={e=>setCreateFilhos(fs=>fs.map((x,idx)=>idx===i?{...x,perfilLeitor:(e.target.value||'') as FilhoForm['perfilLeitor']}:x))} className="w-full mt-1 px-3 py-2 rounded-md border bg-white"><option value="">—</option><option value="iniciante">iniciante</option><option value="Dislexia">Dislexia</option><option value="autonomo">autonomo</option></select></div><div className="sm:col-span-5 -mt-1"><button type="button" onClick={()=>removeFilho(i)} className="text-sm text-red-600 hover:underline">Remover</button></div></div>))}</div>
      <div className="mt-6 flex items-center justify-end gap-2"><button type="button" onClick={()=>setShowCreate(false)} className="px-4 py-2 rounded-md border border-gray-300 bg-white hover:bg-gray-50">Cancelar</button><button type="submit" className="px-4 py-2 rounded-md bg-gradient-to-r from-blue-600 to-purple-600 text-white shadow">Criar</button></div>
    </form></div>)}

    {/* MODAL: EDITAR */}
    {showEditId&&editData&&(<div className="fixed inset-0 z-50 bg-black/30 backdrop-blur-sm flex items-center justify-center p-3"><form onSubmit={handleUpdate} className="w-full max-w-2xl bg-white rounded-2xl shadow-xl border p-5 relative"><button type="button" onClick={()=>{setShowEditId(null);setEditData(null)}} className="absolute right-3 top-3 text-gray-500 hover:text-gray-800"><FaTimes/></button><h2 className="text-xl font-bold mb-4">Editar Família</h2>
      <div className="grid sm:grid-cols-2 gap-4">
        <div><label className="text-sm text-gray-700">Telefone</label><input value={editData.telefone} onChange={e=>setEditData(d=>d?{...d,telefone:e.target.value}:d)} className="w-full mt-1 px-3 py-2 rounded-md border"/></div>
        <div><label className="text-sm text-gray-700">Morada</label><input value={editData.morada} onChange={e=>setEditData(d=>d?{...d,morada:e.target.value}:d)} className="w-full mt-1 px-3 py-2 rounded-md border"/></div>
        <div className="sm:col-span-2"><label className="text-sm text-gray-700">Interesses (CSV)</label><input value={editData.interessesCsv} onChange={e=>setEditData(d=>d?{...d,interessesCsv:e.target.value}:d)} className="w-full mt-1 px-3 py-2 rounded-md border"/></div>
        <div className="sm:col-span-2 mt-2 border-t pt-3"><h3 className="font-semibold mb-2">Dados do utilizador (opcional)</h3><div className="grid sm:grid-cols-2 gap-4">
          <div><label className="text-sm text-gray-700">Nome</label><input value={editData.user.name} onChange={e=>setEditData(d=>d?{...d,user:{...d.user,name:e.target.value}}:d)} className="w-full mt-1 px-3 py-2 rounded-md border"/></div>
          <div><label className="text-sm text-gray-700">Email</label><input type="email" value={editData.user.email} onChange={e=>setEditData(d=>d?{...d,user:{...d.user,email:e.target.value}}:d)} className="w-full mt-1 px-3 py-2 rounded-md border"/></div>
          <div className="sm:col-span-2"><label className="text-sm text-gray-700">Biblioteca</label><select value={editData.user.bibliotecaId===''?'':editData.user.bibliotecaId??''} onChange={e=>{const v=e.target.value;setEditData(d=>d?{...d,user:{...d.user,bibliotecaId:v===''?'':Number(v)}}:d)}} className="w-full mt-1 px-3 py-2 rounded-md border bg-white"><option value="">(não alterar / sem biblioteca)</option>{bibliotecas.map(b=>(<option key={b.id} value={String(b.id)}>{b.nome}</option>))}</select><p className="text-xs text-gray-500 mt-1">A alteração da biblioteca do utilizador só é permitida a administradores (o backend valida).</p></div>
        </div></div>
      </div>
      <div className="mt-6 flex items-center justify-end gap-2"><button type="button" onClick={()=>{setShowEditId(null);setEditData(null)}} className="px-4 py-2 rounded-md border border-gray-300 bg-white hover:bg-gray-50">Cancelar</button><button type="submit" className="px-4 py-2 rounded-md bg-gradient-to-r from-blue-600 to-purple-600 text-white shadow">Guardar</button></div>
    </form></div>)}

    {/* MODAL: DETALHES */}
    {showDetailsId&&(<div className="fixed inset-0 z-50 bg-black/30 backdrop-blur-sm flex items-center justify-center p-3"><div className="w-full max-w-5xl relative"><button type="button" onClick={()=>{setShowDetailsId(null);setDetailsData(null);setDetRequisicoes([]);setDetCompras([]);setDetConsultas([])}} className="absolute -top-2 right-0 text-black" title="Fechar"><FaTimes size={22}/></button>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-0 rounded-2xl shadow-2xl ring-3 ring-blue-600 overflow-hidden bg-[#fffdf7]">
        <div className="p-5 lg:p-6 border-b lg:border-b-0 lg:border-r border-blue-200 bg-white">
          {detailsLoading&&(<div className="py-10 text-center text-gray-600">A carregar…</div>)}
          {!detailsLoading&&detailsData&&(<div className="space-y-4">
            <header className="font-serif"><h3 className="text-2xl font-bold tracking-tight">{detailsData.nome??detailsData.user?.name??`Família #${detailsData.id}`}</h3><p className="text-sm text-gray-600">ID: {detailsData.id} · Criada: {formatDate(detailsData.createdAt)}</p>
              <div className="mt-2"></div>
            </header>
            <div className="grid grid-cols-1 gap-3">
              <div className="rounded-xl border border-blue-200/60 bg-blue-50/30 p-3"><div className="text-xs text-gray-500 mb-1">Responsável</div><div className="font-medium">{detailsData.user?.name??'—'}</div><div className="text-sm text-gray-700">{detailsData.user?.email??'—'}</div><div className="text-sm text-gray-700">Biblioteca: {detailsData.bibliotecaNome??detailsData.user?.biblioteca?.nome??'—'}</div></div>
              <div className="rounded-xl border border-blue-200/60 bg-blue-50/30 p-3"><div className="text-xs text-gray-500 mb-1">Contacto</div><div className="text-sm"><strong>Telefone:</strong> {detailsData.telefone??'—'}</div><div className="text-sm"><strong>Morada:</strong> {detailsData.morada??'—'}</div></div>
            </div>
            <div className="rounded-xl border border-blue-200/60 bg-blue-50/30 p-3"><div className="text-xs text-gray-500 mb-2">Interesses</div><div className="flex flex-wrap gap-2">{(Array.isArray(detailsData.interesses)?detailsData.interesses:[]).length? (detailsData.interesses as string[]).map((i,idx)=>(<Chip key={`${i}-${idx}`}>{i}</Chip>)):(<span className="text-sm text-gray-500">Sem interesses registados.</span>)}</div></div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              <div className="rounded-xl border border-blue-200/60 bg-white p-3"><div className="flex items-center gap-2 text-gray-700"><FaBook/> Requisições</div><div className="mt-1 text-2xl font-bold">{detMetrics.requisicoes}</div></div>
              <div className="rounded-xl border border-blue-200/60 bg-white p-3"><div className="flex items-center gap-2 text-gray-700"><FaShoppingCart/> Compras</div><div className="mt-1 text-2xl font-bold">{detMetrics.compras}</div></div>
              <div className="rounded-xl border border-blue-200/60 bg-white p-3"><div className="flex items-center gap-2 text-gray-700"><FaCalendarAlt/> Consultas</div><div className="mt-1 text-2xl font-bold">{detMetrics.consultas}</div></div>
              <div className="rounded-xl border border-blue-200/60 bg-white p-3"><div className="flex items-center gap-2 text-gray-700"><FaUsers/> Filhos</div><div className="mt-1 text-2xl font-bold">{detMetrics.filhos}</div></div>
            </div>
          </div>)}
          {!detailsLoading&&!detailsData&&(<div className="py-10 text-center text-gray-600">Não foi possível carregar os detalhes.</div>)}
        </div>
        <div className="p-0 bg-white">
          <div className="border-b border-blue-200/80 bg-blue-50/40 px-3 sm:px-4"><div className="flex flex-wrap gap-1 sm:gap-2">{[
            {k:'resumo',label:'Resumo'},{k:'requisicoes',label:'Requisições'},{k:'compras',label:'Compras'},{k:'consultas',label:'Consultas'},{k:'filhos',label:'Filhos'}].map(t=>(<button key={t.k} className={`px-3 py-2 text-sm rounded-t-lg border-b-2 ${detailsTab===(t.k as any)?'border-blue-600 text-blue-900 font-semibold':'border-transparent text-gray-600 hover:text-gray-900'}`} onClick={()=>setDetailsTab(t.k as any)}>{t.label}</button>))}</div></div>
          <div className="p-4 sm:p-5 h-[60vh] overflow-auto">
            {detailsTab==='resumo'&&(<div className="grid gap-4">
              <section className="rounded-lg border border-blue-200/60"><header className="px-3 py-2 border-b bg-blue-50/40 text-sm font-semibold">Últimas requisições</header><ul className="divide-y">{detRequisicoes.slice(0,5).map(r=>(<li key={r.id} className="px-3 py-2 text-sm"><div className="font-medium">{r.titulo??`Requisição #${r.id}`}</div><div className="text-gray-600">{r.estado??'—'} · {r.data?formatDate(r.data):'—'}{r.devolucao&&(<> · Devolução: {formatDate(r.devolucao)}</>)}</div></li>))}{!detRequisicoes.length&&(<li className="px-3 py-3 text-sm text-gray-500">Sem registos.</li>)}</ul></section>
              <section className="rounded-lg border border-blue-200/60"><header className="px-3 py-2 border-b bg-blue-50/40 text-sm font-semibold">Últimas compras</header><ul className="divide-y">{detCompras.slice(0,5).map(c=>(<li key={c.id} className="px-3 py-2 text-sm"><div className="font-medium">{c.titulo??`Compra #${c.id}`}</div><div className="text-gray-600">{c.data?formatDate(c.data):'—'}{typeof c.preco==='number'&&(<> · {c.preco.toFixed(2)} €</>)}{typeof c.qtd==='number'&&(<> · {c.qtd} item(ns)</>)}</div></li>))}{!detCompras.length&&(<li className="px-3 py-3 text-sm text-gray-500">Sem registos.</li>)}</ul></section>
              <section className="rounded-lg border border-blue-200/60"><header className="px-3 py-2 border-b bg-blue-50/40 text-sm font-semibold">Próximas/últimas consultas</header><ul className="divide-y">{detConsultas.slice(0,5).map(c=>(<li key={c.id} className="px-3 py-2 text-sm"><div className="font-medium">{formatDate(c.dataHora)}</div><div className="text-gray-600">{c.bibliotecarioNome??'—'} · {c.status??'—'} {c.metodo?`· ${c.metodo}`:''}</div></li>))}{!detConsultas.length&&(<li className="px-3 py-3 text-sm text-gray-500">Sem registos.</li>)}</ul></section>
            </div>)}
            {detailsTab==='requisicoes'&&(<div className="rounded-lg border border-blue-200/60 overflow-auto"><table className="min-w-full text-sm"><thead className="bg-blue-50/60 text-left text-gray-700"><tr><th className="px-3 py-2">Título</th><th className="px-3 py-2">Estado</th><th className="px-3 py-2">Requisitado</th><th className="px-3 py-2">Devolução</th></tr></thead><tbody>{detRequisicoes.length?detRequisicoes.map(r=>(<tr key={r.id} className="border-t"><td className="px-3 py-2">{r.titulo??`Requisição #${r.id}`}</td><td className="px-3 py-2">{r.estado??'—'}</td><td className="px-3 py-2">{r.data?formatDate(r.data):'—'}</td><td className="px-3 py-2">{r.devolucao?formatDate(r.devolucao):'—'}</td></tr>)):(<tr><td className="px-3 py-3 text-gray-500" colSpan={4}>Sem registos.</td></tr>)}</tbody></table></div>)}
            {detailsTab==='compras'&&(<div className="rounded-lg border border-blue-200/60 overflow-auto"><table className="min-w-full text-sm"><thead className="bg-blue-50/60 text-left text-gray-700"><tr><th className="px-3 py-2">Título/Encomenda</th><th className="px-3 py-2">Data</th><th className="px-3 py-2">Qtd</th><th className="px-3 py-2">Total (€)</th></tr></thead><tbody>{detCompras.length?detCompras.map(c=>(<tr key={c.id} className="border-t"><td className="px-3 py-2">{c.titulo??`Compra #${c.id}`}</td><td className="px-3 py-2">{c.data?formatDate(c.data):'—'}</td><td className="px-3 py-2">{typeof c.qtd==='number'?c.qtd:'—'}</td><td className="px-3 py-2">{typeof c.preco==='number'?c.preco.toFixed(2):'—'}</td></tr>)):(<tr><td className="px-3 py-3 text-gray-500" colSpan={4}>Sem registos.</td></tr>)}</tbody></table></div>)}
            {detailsTab==='consultas'&&(<div className="rounded-lg border border-blue-200/60 overflow-auto"><table className="min-w-full text-sm"><thead className="bg-blue-50/60 text-left text-gray-700"><tr><th className="px-3 py-2">Data/Hora</th><th className="px-3 py-2">Bibliotecário</th><th className="px-3 py-2">Estado</th><th className="px-3 py-2">Método</th></tr></thead><tbody>{detConsultas.length?detConsultas.map(c=>(<tr key={c.id} className="border-t"><td className="px-3 py-2">{formatDate(c.dataHora)}</td><td className="px-3 py-2">{c.bibliotecarioNome??'—'}</td><td className="px-3 py-2">{c.status??'—'}</td><td className="px-3 py-2">{c.metodo??'—'}</td></tr>)):(<tr><td className="px-3 py-3 text-gray-500" colSpan={4}>Sem registos.</td></tr>)}</tbody></table></div>)}
            {detailsTab==='filhos'&&(<div className="rounded-lg border border-blue-200/60 overflow-auto"><table className="min-w-full text-sm"><thead className="bg-blue-50/60 text-left text-gray-700"><tr><th className="px-3 py-2">Nome</th><th className="px-3 py-2">Idade</th><th className="px-3 py-2">Género</th><th className="px-3 py-2">Perfil de Leitor</th></tr></thead><tbody>{Array.isArray(detailsData?.filhos)&&(detailsData!.filhos as FamiliaFilho[]).length?(detailsData!.filhos as FamiliaFilho[]).map((f,i)=>(<tr key={f.id??`${f.nome}-${i}`} className="border-t"><td className="px-3 py-2">{f.nome}</td><td className="px-3 py-2">{f.idade}</td><td className="px-3 py-2">{f.genero}</td><td className="px-3 py-2">{f.perfilLeitor}</td></tr>)):(<tr><td className="px-3 py-3 text-gray-500" colSpan={4}>Nenhum filho registado.</td></tr>)}</tbody></table></div>)}
          </div>
        </div>
      </div>
    </div></div>)}
  </div>)
}
